# Set up data
```{r setup}
library(knitr)
opts_knit$set(root.dir = normalizePath('../'))
```

# Configure models
```{r}
library(ProjectTemplate); load.project()
# set.seed(1234)
source('jags/jags-data-model.r')

# create test dataset
w10 <- rcases[rcases$waves_completed >= 9, "user_id"]
w10 <- sample(w10, 30)
cclong10 <- cclong[ cclong$user_id %in% w10, ]


# analysis_mode is used to control
# configuration can be passed using the makefile
# quick: used to test functionality
# standard: used to get reasonable answer to question
# publication: used for publication quality output
if(!exists("analysis_mode")) analysis_mode <- "quick"
settings <- set_analysis(analysis_mode)


if (analysis_mode == "quick") {
    settings$n.chains <- 2
    DATASET <- cclong10
}
if (analysis_mode == "standard") {
    DATASET <- cclong
    settings <- list(n.chains= 2,  n.adapt= 500, burnin = 4000, n.iter= 1000, thin=2) # around 1 hour - multicore
}
if (analysis_mode == "publication") {
    DATASET <- cclong
    settings <- list(n.chains= 4,  n.adapt= 500, burnin = 5000, n.iter= 5000, thin=1) # around 2 hours - multicore
}


```





# get data
```{r}
source('jags/jags-data-model.r')

model_specifications <- expand.grid(random_error = c(FALSE, TRUE), 
                                    linear_quadratic = c(FALSE, TRUE), 
                                    lag_effect =  c(FALSE, TRUE),
                                    dv=c("pwi_mean", "pwi_mean_probit"),
                                    stringsAsFactors=FALSE)
model_specifications$id <- seq(nrow(model_specifications))
model_specifications$transformed <- model_specifications$dv == "pwi_mean_probit"
model_specifications$name <- with(model_specifications, paste0(ifelse(random_error, "rerr", "ferr"), "_", 
                                                               ifelse(lag_effect, "lagTR", "lagFA"), "_", 
                                                               ifelse(linear_quadratic, "linquad", "int"), "_",
                                                               dv))

fityhat_jags_model <- function(i, dataset=DATASET, spec = model_specifications, ...) {
    model_name <- spec[i, 'name']
    print(model_name)
    data <- get_data(dv=spec[i, 'dv'], data=dataset) # UPDATE cclong10 for final analysis
    
    script <- jags_model(random_error = spec[i, 'random_error'], 
                         # lag = model_specifications[i, 'lag'], 
                         linear_quadratic = spec[i, 'linear_quadratic'], 
                         lag_effect = spec[i, 'lag_effect'],
                         ypred=TRUE, deviance=FALSE, age_effect = TRUE, transformed = spec[i,'transformed'])
    agefit <- lm(y ~ age + I(age^2) + I(age^3),  data.frame(y=data$jagsdata$y, age=data$jagsdata$age))
    run_jags(script$script, data$jagsdata, "ypred", dic.run=FALSE, showplots = FALSE, showsamples = FALSE,
             inits = list(mu_beta_intercept = mean(data$jagsdata$y),
                           sigma_fixed_y = mean(sapply(split(data$jagsdata$y, data$jagsdata$subject), sd)),
                          mu_beta_sigma = log(mean(sapply(split(data$jagsdata$y, data$jagsdata$subject), sd))),
                          mu_beta_lag = 0.2 ,    
                          theta_age_linear = coef(agefit)['age'],
                             theta_age_quadratic = coef(agefit)['I(age^2)'],
                             theta_age_cubic = coef(agefit)['I(age^3)'] 
                    ) ,
             ...)
}

modelfit <- fityhat_jags_model( which(model_specifications$random_error == TRUE & 
              model_specifications$lag_effect == FALSE &
              model_specifications$linear_quadratic == FALSE & 
              model_specifications$dv == "pwi_mean_probit"))
yhats <- modelfit$samples
save(modelfit, file = "output/yhats-individual.rdata")
```

# Group level plot
```{r}
load(file="output/model-fits.rdata")
# mf <- fits$rerr_lagFA_int_pwi_mean_probit
mf <- fits$rerr_lagFA_int_pwi_mean_probit
mfs <- combine.mcmc(mf$samples)
mfs <- data.frame(mfs)

df <- data.frame(age=seq(round(sort(cclong$age_est)[100]), round(sort(cclong$age_est)[nrow(cclong) - 100])))
df$age_centered <- df$age - 62 # check centered age


age_estimates <- function(i)  {
    x <- with(mfs[i, ],  mu_beta_intercept + theta_age_linear * df$age_centered + 
                                        theta_age_quadratic * df$age_centered ^2 +
                                        theta_age_cubic *  df$age_centered ^3)
    x <- (pnorm(x) * 11) - 0.5
}

xs <- sapply(seq(nrow(mfs)), age_estimates)
df$yhat_mean <- apply(xs, 1, mean)
df$yhat_lower <- apply(xs, 1, function(X) quantile(X, .025))
df$yhat_upper <- apply(xs, 1, function(X) quantile(X, .975))


p <- ggplot(cclong, aes(x=age_est, y=pwi_mean)) + 
    geom_point(position=position_jitter(width=.05), size=1) 
p <- p + geom_line(data=df, aes(x=age, y=yhat_mean))
p <- p + scale_x_continuous(name="Age (years)") +
     scale_y_continuous(name="Subjective Well-Being (0 - 10)")
p <- p + geom_ribbon(data=df, aes(x=age, y=yhat_mean, ymin=yhat_lower, ymax=yhat_upper), alpha=0.3)
p

pdf("output/group-level-pwi.pdf", width = 10, height=8)
p 
dev.off()
```




# Individual level plot
```{r}
source("lib/extract-parameters.R")
# load("output/yhats-individual.rdata")
# DATASET <- cclong
# step 1 get yhat 
# Step 2 merge yhat into cctrials


# yhats <- modelfit$samples
merge_yhats <- function(model) {
    yhats <- model$samples
    yhats <- combine.mcmc(yhats)
    yhv <- list()
    yhv$mean <- extract_parameter(yhats, "ypred", mean)
    yhv$lower <- extract_parameter(yhats, "ypred", function(X) quantile(X, .025))
    yhv$upper <- extract_parameter(yhats, "ypred", function(X) quantile(X, .975))
    yhv$combined <- data.frame(yhat_mean=yhv$mean[,2], yhat_lower=yhv$lower[,2], yhat_upper = yhv$upper  [,2])
    yhv$combined$observationid <-  model$data$observationid

    merge(yhv$combined, DATASET, by.x='observationid', by.y="wave_id")
}

plot_subset <- function(subset, plot_title="") {
    yhds <- yhd[ yhd$user_id %in% subset, ]   
    yhds <- yhds[ order(yhds$observationid, yhds$time0), ]
    # lapply(subset, function(i) with(yhds[yhds$user_id %in% i, ], cbind(time0, age_est)))

    p <- ggplot(yhds, aes(time0, pwi_mean)) + geom_point() 
    p <- p + geom_line(aes(x=time0, y=yhat_mean))
    p <- p   + scale_y_continuous("Subjective Well-Being (0 - 10)", limits=c(-0.5, 10.5)) + 
         scale_x_continuous("Measurement occasion",  limits=c(-0.5, 9.5), breaks=c(0,1,2,3,4,5,6,7,8,9))
    p <- p + geom_ribbon(aes(ymin=yhat_lower, ymax=yhat_upper), alpha=0.3)
    p <- p + facet_wrap(~user_id, ncol=3) 
    p <- p + ggtitle(plot_title)
    p

}

set.seed(1234)
w10 <- rcases[rcases$waves_completed >= 10, "user_id"]
length(w10)
w10 <- sample(w10, 15)
# debugonce(plot_subset)

pcomb <- list()
# debugonce(merge_yhats)
yhd <- merge_yhats(modelfit$rerr_lagFA_int_pwi_mean_probit)
pcomb$rerr_lagFA_int_pwi_mean_probit <- plot_subset(subset = w10, plot_title = "(a) Random Intercept")

yhd <- merge_yhats(modelfit$rerr_lagFA_linquad_pwi_mean_probit)
pcomb$rerr_lagFA_linquad_pwi_mean_probit <- plot_subset(subset = w10, plot_title="(b) Random Intercept, Linear, and Quadratic")


grid.arrange(pcomb$rerr_lagFA_int_pwi_mean_probit, pcomb$rerr_lagFA_linquad_pwi_mean_probit, ncol=2)

pdf(file="output/individual-fits.pdf", width=10, height=8)
grid.arrange(pcomb$rerr_lagFA_int_pwi_mean_probit, pcomb$rerr_lagFA_linquad_pwi_mean_probit, ncol=2)
dev.off()

```